;; knoq-your-css-well.el
;;
;; Emacs extension inspired by https://github.com/for-GET/know-your-http-well but for css
;;
;; Usage:
;;
;; 0xAX

(defconst css-properties
  '(("background" ("CSS background properties are used to define the background effects of an element.CSS properties used for background effects:\nbackground-color\nbackground-image\nbackground-repeat\nbackground-attachment\nbackground-position"))
    ("background-attachment" ("The background-attachment property sets whether a background image is fixed or scrolls with the rest of the page.\nbackground-attachment: scroll|fixed|local|initial|inherit;\nscroll - The background scrolls along with the element. This is default\nfixed - The background is fixed with regard to the viewport\nlocal- The background scrolls along with the element's contents\ninitial - Sets this property to its default value.\ninherit - Inherits this property from its parent element."))
    ("background-clip" ("The background-clip property is supported in Internet Explorer 9+, Firefox, Opera, Chrome, and Safari.\nbackground-clip: border-box|padding-box|content-box|initial|inherit;\nborder-box - Default value. The background is clipped to the border box\npadding-box - The background is clipped to the padding box\ncontent-box - The background is clipped to the content box\ninitial - Sets this property to its default value.\ninherit - Inherits this property from its parent element."))
    ("background-color" ("The background-color property sets the background color of an element.\nbackground-color: color|transparent|initial|inherit;"))
    ("background-image" ("The background-image property sets one or more background images for an element.\nbackground-image: url|none|initial|inherit;"))
    ("background-origin" ("The background-origin property specifies what the background-position property should be relative to.\nbackground-origin: padding-box|border-box|content-box|initial|inherit;"))
    ("background-position" ("The background-position property sets the starting position of a background image.\nbackground-position: value;"))
    ("background-repeat" ("The background-repeat property sets if/how a background image will be repeated.\nbackground-repeat: repeat|repeat-x|repeat-y|no-repeat|initial|inherit;"))
    ("background-size-border" ("The background-size property specifies the size of the background images.background-size: auto|length|cover|contain|intial|inherit;"))
    ("background-bottom" ("The border-bottom shorthand property sets all the bottom border properties in one declaration.\nborder-bottom: border-width border-style border-color|initial|inherit;"))
    ("background-bottom-color" ("The border-bottom-color property sets the color of an element's bottom border.\nborder-bottom-color: color|transparent|initial|inherit;"))
    ("border-bottom-left-radius" ("The border-bottom-left-radius property defines the shape of the border of the bottom-left corner.\nborder-bottom-left-radius: length|% [length|%]|initial|inherit;"))
    ("border-bottom-right-radius" ("The border-bottom-right-radius property defines the shape of the border of the bottom-right corner.\nborder-bottom-right-radius: length|% [length|%]|initial|inherit;"))
    ("border-bottom-style" ("The border-bottom-style property sets the style of an element's bottom border.\nborder-bottom-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("border-bottom-width" ("The border-bottom-width property sets the width of an element's bottom border.\nborder-bottom-width: medium|thin|thick|length|initial|inherit;"))
    ("border-collapse" ("The border-collapse property sets whether the table borders are collapsed into a single border or detached as in standard HTML.\nborder-collapse: separate|collapse|initial|inherit;"))
    ("border-color" ("The border-color property sets the color of an element's four borders. This property can have from one to four values.\nborder-color: color|transparent|initial|inherit;"))
    ("border-image" ("The border-image property is a shorthand property for setting the border-image-source, border-image-slice, border-image-width, border-image-outset and border-image-repeat properties."))
    ("border-left" ("border-left: border-width border-style border-color|initial|inherit;"))
    ("border-left-color" ("The border-left-color property sets the color of an element's left border.\nborder-left-color: color|transparent|initial|inherit;"))
    ("border-left-style" ("The border-left-style property sets the style of an element's left border.\nborder-left-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("border-left-width" ("The border-left-width property sets the width of an element's left border.\nborder-left-width: medium|thin|thick|length|initial|inherit;"))
    ("border-radius" ("The border-radius property is a shorthand property for setting the four border-*-radius properties.\nborder-radius: 1-4 length|% / 1-4 length|%|initial|inherit;"))
    ("border-right" ("The border-right shorthand property sets all the right border properties in one declaration.\nborder-right: border-width border-style border-color|initial|inherit;"))
    ("border-right-color" ("The border-right-color property sets the color of an element's right border.\nborder-right-color: color|transparent|initial|inherit;"))
    ("border-right-style" ("The border-right-style property sets the style of an element's right border.\nborder-right-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("border-right-width" ("The border-right-width property sets the width of an element's right border.\nborder-right-width: medium|thin|thick|length|initial|inherit;"))
    ("border-spacing" ("The border-spacing property sets the distance between the borders of adjacent cells (only for the "separated borders" model).\nborder-spacing: length|initial|inherit;"))
    ("border-style" ("The border-style property sets the style of an element's four borders. This property can have from one to four values.\nborder-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("border-top" ("The border-top shorthand property sets all the top border properties in one declaration.\nborder-top: border-width border-style border-color|initial|inherit;"))
    ("border-top-color" ("The border-top-color property sets the color of an element's top border.\nborder-top-color: color|transparent|initial|inherit;"))
    ("border-top-left-radius" ("The border-top-left-radius property defines the shape of the border of the top-left corner.\nborder-top-left-radius: length|% [length|%]|initial|inherit;"))
    ("border-top-right-radius" ("The border-top-right-radius property defines the shape of the border of the top-right corner.\nborder-top-right-radius: length|% [length|%]|initial|inherit;"))
    ("border-top-style" ("The border-top-style property sets the style of an element's top border.\nborder-top-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("border-top-width" ("The border-top-width property sets the width of an element's top border.\nborder-top-width: medium|thin|thick|length|initial|inherit;"))
    ("bottom" ("For absolutely positioned elements, the bottom property sets the bottom edge of an element to a unit above/below the bottom edge of its containing element.\nbottom: auto|length|initial|inherit;"))
    ("box-shadow" ("The box-shadow property attaches one or more drop-shadows to the box.\nbox-shadow: none|h-shadow v-shadow blur spread color |inset|initial|inherit;"))
    ("box-sizing" ("The box-sizing property allows you to define certain elements to fit an area in a certain way.\nbox-sizing: content-box|border-box|initial|inherit;"))
    ("caption-side" ("The caption-side property specifies the placement of a table caption.\ncaption-side: top|bottom|initial|inherit;"))
    ("clear" ("The clear property specifies which side(s) of an element other floating elements are not allowed.\nclear: none|left|right|both|initial|inherit;"))
    ("clip" ("What happens if an image is larger than its containing element? - The clip property lets you specify a rectangle to clip an absolutely positioned element. The rectangle is specified as four coordinates, all from the top-left corner of the element to be clipped.\nclip: auto|shape|initial|inherit;"))
    ("color" ("The color property specifies the color of text.\ncolor: color|initial|inherit;"))
    ("column-count" ("The column-count property specifies the number of columns an element should be divided into.\ncolumn-count: number|auto|initial|inherit;"))
    ("column-gap" ("The column-gap property specifies the gap between the columns.\ncolumn-gap: length|normal|initial|inherit;"))
    ("column-rule" ("The column-rule property is a shorthand property for setting all the column-rule-* properties.\ncolumn-rule: column-rule-width column-rule-style column-rule-color|initial|inherit;"))
    ("column-width" ("The column-width property specifies the width of the columns.\ncolumn-width: auto|length|initial|inherit;"))
    ("columns" ("The columns property is a shorthand property for setting column-width and column-count.\ncolumns: auto|column-width column-count|initial|inherit;"))
    ("content" ("The content property is used with the :before and :after pseudo-elements, to insert generated content.\ncontent: normal|none|counter|attr|string|open-quote|close-quote|no-open-quote|no-close-quote|url|initial|inherit;"))
    ("counter-increment" ("The counter-increment property increments one or more counter values.\ncounter-increment: none|id|initial|inherit;"))
    ("counter-reset" ("The counter-reset property creates or resets one or more counters.\ncounter-reset: none|name number|initial|inherit;"))
    ("cursor" ("The cursor property specifies the type of cursor to be displayed when pointing on an element.\ncursor: value;"))
    ("direction" ("The direction property specifies the text direction/writing direction.\ndirection: ltr|rtl|initial|inherit;"))
    ("display" ("The display property specifies the type of box used for an HTML element.\ndisplay: value;"))
    ("empty-cells" ("The empty-cells property sets whether or not to display borders and background on empty cells in a table\nempty-cells: show|hide|initial|inherit;"))
    ("font" ("The font shorthand property sets all the font properties in one declaration.\nfont: font-style font-variant font-weight font-size/line-height|caption|icon|menu|message-box|small-caption|status-bar|initial|inherit;"))
    ("font-family" ("The font-family property specifies the font for an element.\nfont-family: font|initial|inherit;"))
    ("float" ("The float property specifies whether or not a box (an element) should float.\nfloat: none|left|right|initial|inherit;"))
    ("font-size" ("The font-size property sets the size of a font.\nfont-size:medium|xx-small|x-small|small|large|x-large|xx-large|smaller|larger|length|initial|inherit;"))
    ("font-stretch" ("The font-stretch property allows you to make text wider or narrower.\nfont-stretch: wider|narrower|ultra-condensed|extra-condensed|condensed|semi-condensed|normal|semi-expanded|expanded|extra-expanded|ultra-expanded|initial|inherit;"))
    ("font-style" ("The font-style property specifies the font style for a text.\nfont-style: normal|italic|oblique|initial|inherit;"))
    ("font-variant" ("In a small-caps font, all lowercase letters are converted to uppercase letters. However, the converted uppercase letters appears in a smaller font size than the original uppercase letters in the text.\nfont-variant: normal|small-caps|initial|inherit;"))
    ("font-weight" ("The font-weight property sets how thick or thin characters in text should be displayed.\nfont-weight: normal|bold|bolder|lighter|number|initial|inherit;"))
    ("height" ("The height property sets the height of an element.\nheight: auto|length|initial|inherit;"))
    ("left" ("For absolutely positioned elements, the left property sets the left edge of an element to a unit to the left/right of the left edge of its containing element.\nleft: auto|length|initial|inherit;"))
    ("line-height" ("The line-height property specifies the line height.\nline-height: normal|number|length|initial|inherit;"))
    ("list-style" ("The list-style shorthand property sets all the list properties in one declaration.\nlist-style: list-style-type list-style-position list-style-image|initial|inherit;"))
    ("list-style-image" ("The list-style-image property replaces the list-item marker with an image.\nlist-style-image: none|url|initial|inherit;"))
    ("list-style-position" ("The list-style-position property specifies if the list-item markers should appear inside or outside the content flow.\nlist-style-position: inside|outside|initial|inherit;"))
    ("list-style-type" ("The list-style-type specifies the type of list-item marker in a list.\nlist-style-type: value;"))
    ("margin" ("The margin shorthand property sets all the margin properties in one declaration. This property can have from one to four values.\nmargin: length|auto|initial|inherit;"))
    ("margin-bottom" ("The margin-bottom property sets the bottom margin of an element.\nmargin-bottom: length|auto|initial|inherit;"))
    ("margin-top" ("The margin-top property sets the top margin of an element.\nmargin-top: length|auto|initial|inherit;"))
    ("margin-left" ("The margin-left property sets the left margin of an element.\nmargin-left: length|auto|initial|inherit;"))
    ("margin-right" ("The margin-right property sets the right margin of an element.\nmargin-right: length|auto|initial|inherit;"))
    ("max-height" ("The max-height property is used to set the maximum height of an element.\nmax-height: none|length|initial|inherit;"))
    ("max-width" ("The max-width property is used to set the maximum width of an element.\nmax-width: none|length|initial|inherit;"))
    ("min-height" ("The min-height property is used to set the minimum height of an element.\nmin-height: none|length|initial|inherit;"))
    ("min-width" ("The min-width property is used to set the minimum width of an element.\nmin-width: none|length|initial|inherit;"))
    ("opacity" ("The opacity property sets the opacity level for an element. The opacity-level describes the transparency-level, where 1 is not transparant at all, 0.5 is 50% see-through, and 0 is completely transparent.\n"))
    ("order" ("The order property specifies the order of a flexible item relative to the rest of the flexible items inside the same container.\norder: number|initial|inherit;"))
    ("outline" ("An outline is a line that is drawn around elements (outside the borders) to make the element 'stand out'.\noutline: outline-color outline-style outline-width|initial|inherit"))
    ("outline-color" ("The outline-color property specifies the color of an outline.\noutline-color: invert|color|initial|inherit;"))
    ("outline-offset" ("The outline-offset property offsets an outline, and draws it beyond the border edge.\noutline-offset: length|initial|inherit;"))
    ("outline-style" ("The outline-style property specifies the style of an outline.\noutline-style: none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;"))
    ("outline-width" ("The outline-width specifies the width of an outline.\noutline-width: medium|thin|thick|length|initial|inherit;"))
    ("overflow" ("The overflow property specifies what happens if content overflows an element's box.\noverflow: visible|hidden|scroll|auto|initial|inherit;"))
    ("overflow-x" ("The overflow-x property specifies what to do with the left/right edges of the content - if it overflows the element's content area.\noverflow-x: visible|hidden|scroll|auto|initial|inherit;"))
    ("overflow-y" ("The overflow-y property specifies what to do with the top/bottom edges of the content - if it overflows the element's content area.\noverflow-y: visible|hidden|scroll|auto|initial|inherit;"))
    ("padding" ("The padding shorthand property sets all the padding properties in one declaration. This property can have from one to four values.\npadding: length|initial|inherit;"))
    ("padding-bottom" ("\npadding-bottom: length|initial|inherit;"))
    ("padding-left" ("The padding-left property sets the left padding (space) of an element.\npadding-left: length|initial|inherit;"))
    ("padding-right" ("The padding-right property sets the right padding (space) of an element.\npadding-right: length|initial|inherit;"))
    ("padding-top" ("The padding-top property sets the top padding (space) of an element.\npadding-top: length|initial|inherit;"))
    ("page-break-after" ("The page-break-after property sets whether a page break should occur AFTER a specified element.\npage-break-after: auto|always|avoid|left|right|initial|inherit;"))
    ("page-bread-before" ("The page-break-before property sets whether a page break should occur BEFORE a specified element.\npage-break-before: auto|always|avoid|left|right|initial|inherit;"))
    ("page-break-inside" ("The page-break-inside property sets whether a page break is allowed inside a specified element.\npage-break-inside: auto|avoid|initial|inherit;"))
    ("position" ("The position property specifies the type of positioning method used for an element (static, relative, absolute or fixed).\nposition: static|absolute|fixed|relative|initial|inherit;"))
    ("quotes" ("The quotes property sets the type of quotation marks for quotations.\nquotes: none|string|initial|inherit;"))
    ("resize" ("The resize property specifies whether or not an element is resizable by the user.\nresize: none|both|horizontal|vertical|initial|inherit;"))
    ("right" ("For absolutely positioned elements, the right property sets the right edge of an element to a unit to the left/right of the right edge of its containing element.\nright: auto|length|initial|inherit;"))
    ("tab-size" ("The table-layout property sets the table layout algorithm to be used for a table.\ntable-layout: auto|fixed|initial|inherit;"))
    ("text-align" ("The text-align property specifies the horizontal alignment of text in an element.\ntext-align: left|right|center|justify|initial|inherit;"))
    ("text-align-last" ("The text-align-last property specifies how to align the last line of a text.\ntext-align-last: auto|left|right|center|justify|start|end|initial|inherit;"))
    ("text-decoration" ("The text-decoration property specifies the decoration added to text.\ntext-decoration: none|underline|overline|line-through|initial|inherit;"))
    ("text-decoration-color" ("The text-decoration-color property is not supported in any of the major browsers.\nThe text-decoration-color property specifies the color of the text-decoration (underlines, overlines, linethroughs)."))
    ("text-decoration-line" ("The text-decoration-line property specifies what type of line, if any, the decoration will have.\ntext-decoration-line: none|underline|overline|line-through|initial|inherit;"))
    ("text-indent" ("The text-indent property specifies the indentation of the first line in a text-block.\ntext-indent: length|initial|inherit;"))
    ("text-overflow" ("The text-overflow property specifies what should happen when text overflows the containing element.\ntext-overflow: clip|ellipsis|string|initial|inherit;"))
    ("text-shadow" ("The text-shadow property applies shadow to text.\ntext-shadow: h-shadow v-shadow blur color|none|initial|inherit;"))
    ("text-transform" ("The text-transform property controls the capitalization of text.\ntext-transform: none|capitalize|uppercase|lowercase|initial|inherit;"))
    ("top" ("For absolutely positioned elements, the top property sets the top edge of an element to a unit above/below the top edge of its containing element.\ntop: auto|length|initial|inherit;"))
    ("transform" ("The transform property applies a 2D or 3D transformation to an element. This property allows you to rotate, scale, move, skew, etc., elements.\ntransform: none|transform-functions|initial|inherit;"))
    ("transform-origin" ("The transform-origin property allows you to change the position on transformed elements.2D transformed element can change the x- and y-axis of the element. 3D transformed element can also change the z-axis of the element.\ntransform-origin: x-axis y-axis z-axis|initial|inherit;"))
    ("transition" ("The transition property is a shorthand property for the four transition properties: transition-property, transition-duration, transition-timing-function, and transition-delay.\ntransition: property duration timing-function delay|initial|inherit;"))
    ("transition-delay" ("The transition-delay property specifies when the transition effect will start.\ntransition-delay: time|initial|inherit;"))
    ("transition-duration" ("The transition-duration property specifies how many seconds (s) or milliseconds (ms) a transition effect takes to complete.\ntransition-duration: time|initial|inherit;"))
    ("transition-property" ("The transition-property property specifies the name of the CSS property the transition effect is for (the transition effect will start when the specified CSS property changes).\ntransition-property: none|all|property|initial|inherit;"))
    ("transition-timing-function" ("The transition-timing-function property specifies the speed curve of the transition effect.\ntransition-timing-function: ease|linear|ease-in|ease-out|ease-in-out|cubic-bezier()|initial|inherit;"))
    ("unicode-bidi" ("The unicode-bidi property is used together with the direction property to set or return whether the text should be overridden to support multiple languages in the same document.\nunicode-bidi: normal|embed|bidi-override|intitial|inherit;\n"))
    ("vertical-align" ("The vertical-align property sets the vertical alignment of an element.\nvertical-align: baseline|length|sub|super|top|text-top|middle|bottom|text-bottom|initial|inherit;"))
    ("visibility" ("The visibility property specifies whether or not an element is visible.\nvisibility: visible|hidden|collapse|initial|inherit;"))
    ("white-space" ("The white-space property specifies how white-space inside an element is handled.\nwhite-space: normal|nowrap|pre|pre-line|pre-wrap|initial|inherit;"))
    ("width" ("The width property sets the width of an element.\nwidth: auto|value|initial|inherit;"))
    ("word-break" ("The word-break property specifies line breaking rules for non-CJK scripts.\nword-break: normal|break-all|keep-all|initial|inherit;"))
    ("word-spacing" ("The word-spacing property increases or decreases the white space between words.\nword-spacing: normal|length|initial|inherit;"))
    ("word-wrap" ("The word-wrap property allows long words to be able to be broken and wrap onto the next line.\nword-wrap: normal|break-word|initial|inherit;"))
    ("z-index" ("The z-index property specifies the stack order of an element. An element with greater stack order is always in front of an element with a lower stack order.\nz-index: auto|number|initial|inherit;"))
   )
)

(defun css-property (method)
  (interactive
   (list (completing-read "Enter CSS property: " css-properties)))
  (let* ((uppercased (downcase method))
        (found (assoc uppercased css-properties)))
    (if found
        (let ((description (car (cdr found))))
          (message
           "%s - CSS property\n%s"
           uppercased (car description) ))
      (message "%s - CSS property\nUNKNOWN" uppercased))
    ))

(provide 'know-your-css-well)
